#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# waybar
$scripts/launch_waybar &
$scripts/tools/dynamic &

# wallpaper
swww-daemon &
$scripts/wall $HOME/Pictures/Wallpapers &

# effects
$scripts/rgb &

# startup apps
rog-control-center &
discord &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
notify-send -a Arch "Hello $(whoami)" &
